version: '3.8'

services:
    worker:
        build:
            context: .
            dockerfile: ./.docker/worker/Dockerfile
        container_name: cms_worker
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - cmstabtab

    server:
        image: nginx:latest
        container_name: cms_server
        volumes:
            - .:/var/www
            - ./.docker/server/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        depends_on:
            - worker
        networks:
            - cmstabtab

    mysql:
        image: mysql:8.0
        container_name: cms_mysql
        command:
            - --innodb-buffer-pool-size=1G
            - --innodb-flush-log-at-trx-commit=0
            - --innodb-log-file-size=1G
            - --max-allowed-packet=100M
            - --innodb-strict-mode=0
        environment:
            MYSQL_DATABASE: tabtab
            MYSQL_USER: tabtab
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3318:3306"
        networks:
            - cmstabtab
    npm:
        image: node:18-alpine
        container_name: cms_npm
        working_dir: /var/www
        command: >
            sh -c "npm install && npm run dev"
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        depends_on:
            - worker
        networks:
            - cmstabtab

networks:
    cmstabtab:
        driver: bridge

volumes:
    mysql_data:
        driver: local
